// GENERATED by test/drift-harness/robustness.mjs — do not hand-edit.
// Per-metric geometric pose sensitivity (bank-SD per degree, per axis).
// From rigid 3D rotations of the 155 frozen bank faces (synthetic probe):
// the causal pose->metric quantity, free of detector noise.
// Empirical detector-in-the-loop slopes live in robustness.json — they are
// UPPER bounds (detector breakdown inflates them at extreme pose) and are not
// used for flagging; the quality gate owns that regime.
export const POSE_SLOPE = {
  face_width_px: [0.0477, 0.0003, 0.0001], // yaw, roll, pitch
  face_height_px: [0.0021, 0.0001, 0.0708], // yaw, roll, pitch
  width_height_ratio: [0.1917, 0.0011, 0.2489], // yaw, roll, pitch
  fwhr_proxy: [0.1192, 0.0007, 0.0796], // yaw, roll, pitch
  jaw_to_cheek: [0.0014, 0, 0], // yaw, roll, pitch
  gonial_angle_L: [0.2345, 0.0019, 0.2847], // yaw, roll, pitch
  gonial_angle_R: [0.0333, 0.0024, 0.2405], // yaw, roll, pitch
  gonial_angle_mean: [0.1012, 0.0004, 0.2764], // yaw, roll, pitch
  third_upper_pct: [0.0075, 0, 0.102], // yaw, roll, pitch
  third_mid_pct: [0.0189, 0, 0.1555], // yaw, roll, pitch
  third_lower_pct: [0.0241, 0, 0.2397], // yaw, roll, pitch
  chin_to_lower_third: [0.0189, 0, 0.0871], // yaw, roll, pitch
  philtrum_to_nose: [0.0067, 0, 0.1098], // yaw, roll, pitch
  ipd_px: [0.0514, 0.0003, 0.0001], // yaw, roll, pitch
  ipd_to_cheek: [0.001, 0, 0], // yaw, roll, pitch
  eye_spacing_widths: [0.0056, 0, 0.0204], // yaw, roll, pitch
  eye_w_to_h: [0.0823, 0.0005, 0.1266], // yaw, roll, pitch
  canthal_tilt_L: [0.0472, 0.0002, 0.1577], // yaw, roll, pitch
  canthal_tilt_R: [-0.0003, 0.0001, 0.1724], // yaw, roll, pitch
  canthal_tilt_mean: [0.0367, 0.0003, 0.2471], // yaw, roll, pitch
  fifths: [0.006, 0, 0.0214], // yaw, roll, pitch
  nose_w_px: [0.0451, 0.0002, 0], // yaw, roll, pitch
  nose_len_px: [0.007, 0.0001, 0.063], // yaw, roll, pitch
  nose_to_cheek: [0.0013, 0, 0.0002], // yaw, roll, pitch
  nose_w_to_intercanthal: [0.0028, 0, 0.0002], // yaw, roll, pitch
  mouth_w_px: [0.0536, 0.0003, 0.0001], // yaw, roll, pitch
  mouth_to_cheek: [0.0009, 0, 0.0001], // yaw, roll, pitch
  mouth_to_nose: [0.0029, 0, 0.0001], // yaw, roll, pitch
  lip_fullness: [0.0406, 0.0002, 0.067], // yaw, roll, pitch
  upper_lower_lip: [0.0582, 0, 0.2844], // yaw, roll, pitch
  brow_eye_dist_pct: [0.0016, 0, 0.0275], // yaw, roll, pitch
  brow_arch_L: [0.1001, 0.0004, 0.2979], // yaw, roll, pitch
  brow_arch_R: [0.0469, 0.0006, 0.309], // yaw, roll, pitch
  brow_arch_mean: [0.0767, 0.0005, 0.3073], // yaw, roll, pitch
  mean_asymmetry: [1.1461, 2.0686, 0], // yaw, roll, pitch
  asymmetry_9: [1.0515, 2.5321, 0], // yaw, roll, pitch
  canthal_tilt_diff: [0.0249, 0.0001, 0.0033], // yaw, roll, pitch
  gonial_diff: [0.4754, 0.0081, 0.0441], // yaw, roll, pitch
  canon_thirds: [0.0075, 0, 0.102], // yaw, roll, pitch
  canon_fifths: [0.006, 0, 0.0212], // yaw, roll, pitch
  canon_nose: [0.0032, 0, 0.0001], // yaw, roll, pitch
  canon_mouth: [0.003, 0, 0.0001], // yaw, roll, pitch
  canon_spacing: [0.0056, 0, 0.0206], // yaw, roll, pitch
};
export const BANK_SD = {
  face_width_px: 55.3059,
  face_height_px: 57.583,
  width_height_ratio: 0.0181,
  fwhr_proxy: 0.0675,
  jaw_to_cheek: 0.0105,
  gonial_angle_L: 1.4723,
  gonial_angle_R: 1.5822,
  gonial_angle_mean: 1.4465,
  third_upper_pct: 0.874,
  third_mid_pct: 0.7267,
  third_lower_pct: 0.8431,
  chin_to_lower_third: 0.0274,
  philtrum_to_nose: 0.0225,
  ipd_px: 23.6705,
  ipd_to_cheek: 0.0095,
  eye_spacing_widths: 0.046,
  eye_w_to_h: 0.1453,
  canthal_tilt_L: 1.1038,
  canthal_tilt_R: 1.0386,
  canthal_tilt_mean: 0.7145,
  fifths: 0.0958,
  nose_w_px: 13.8153,
  nose_len_px: 15.2305,
  nose_to_cheek: 0.0137,
  nose_w_to_intercanthal: 0.0404,
  mouth_w_px: 19.501,
  mouth_to_cheek: 0.0154,
  mouth_to_nose: 0.0513,
  lip_fullness: 0.0447,
  upper_lower_lip: 0.0365,
  brow_eye_dist_pct: 0.8132,
  brow_arch_L: 0.0175,
  brow_arch_R: 0.0163,
  brow_arch_mean: 0.0167,
  mean_asymmetry: 0.0166,
  asymmetry_9: 0.0168,
  canthal_tilt_diff: 1.5977,
  gonial_diff: 0.8226,
  canon_thirds: 0.874,
  canon_fifths: 1.9053,
  canon_nose: 3.5793,
  canon_mouth: 3.2812,
  canon_spacing: 2.2973,
};
export const ROBUSTNESS_TIER = {
  face_width_px: 'robust',
  face_height_px: 'moderate',
  width_height_ratio: 'fragile',
  fwhr_proxy: 'fragile',
  jaw_to_cheek: 'robust',
  gonial_angle_L: 'fragile',
  gonial_angle_R: 'fragile',
  gonial_angle_mean: 'fragile',
  third_upper_pct: 'fragile',
  third_mid_pct: 'fragile',
  third_lower_pct: 'fragile',
  chin_to_lower_third: 'moderate',
  philtrum_to_nose: 'fragile',
  ipd_px: 'moderate',
  ipd_to_cheek: 'robust',
  eye_spacing_widths: 'robust',
  eye_w_to_h: 'fragile',
  canthal_tilt_L: 'fragile',
  canthal_tilt_R: 'fragile',
  canthal_tilt_mean: 'fragile',
  fifths: 'robust',
  nose_w_px: 'robust',
  nose_len_px: 'moderate',
  nose_to_cheek: 'robust',
  nose_w_to_intercanthal: 'robust',
  mouth_w_px: 'moderate',
  mouth_to_cheek: 'robust',
  mouth_to_nose: 'robust',
  lip_fullness: 'moderate',
  upper_lower_lip: 'fragile',
  brow_eye_dist_pct: 'robust',
  brow_arch_L: 'fragile',
  brow_arch_R: 'fragile',
  brow_arch_mean: 'fragile',
  mean_asymmetry: 'fragile',
  asymmetry_9: 'fragile',
  canthal_tilt_diff: 'robust',
  gonial_diff: 'fragile',
  roll_deg: 'fragile',
  yaw_deg: 'fragile',
  pitch_deg: 'unknown',
  yaw_proxy_deg: 'fragile',
  frontality: 'fragile',
  canon_thirds: 'fragile',
  canon_fifths: 'robust',
  canon_nose: 'robust',
  canon_mouth: 'robust',
  canon_spacing: 'robust',
};
// Expected pose-induced deviation (bank-SD units), linearized worst case:
// sum over axes of slope_axis * |angle_axis|. A lower bound on total doubt —
// detector breakdown at extreme pose adds unmodeled error on top.
export function poseErrorEstimate(key, yawDeg, rollDeg, pitchDeg) {
  const s = POSE_SLOPE[key];
  if (!s) return null;
  return s[0] * Math.abs(yawDeg || 0) + s[1] * Math.abs(rollDeg || 0) + s[2] * Math.abs(pitchDeg || 0);
}
// Flag level for a capture's pose: 'ok' | 'pose-suspect' (>=0.5 SD) | 'pose-unreliable' (>=1 SD)
export function poseFlagFor(key, yawDeg, rollDeg, pitchDeg) {
  const e = poseErrorEstimate(key, yawDeg, rollDeg, pitchDeg);
  if (e == null) return 'ok';
  if (e >= 1) return 'pose-unreliable';
  if (e >= 0.5) return 'pose-suspect';
  return 'ok';
}
